---
title: "Pre-Made Visualizations"
author: "Nick Brinkmann"
date: "12/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gganimate)
library(lubridate)
library(ggrepel)
library(wesanderson)
library(ggthemes)
library(rstanarm)
```

## Creating Visualizations
```{r}
all_games <- readRDS("all_games.RDS")
all_games_dense <- readRDS("all_games_dense.RDS")
```


```{r elo_plot_smoother}
# Creating a plot using average Elo for each day, to mitigate large deviations
# in rating over a single day. Makes plot smoother

elo_by_day <- all_games %>% 
  group_by(Date, website, format) %>% 
  summarize(avg_daily_elo = mean(my_elo))

elo_by_day %>% 
ggplot(aes(x = Date, 
             y = avg_daily_elo,
                 group = format,
                 color = factor(format))) +
  geom_line(na.rm = TRUE) +
  facet_wrap(~ website) +
  labs(title = "Elo Rating Over Time, by Website and Time Control", 
       y = "Elo Rating",
       caption = "Source: Self-collected data") +
  ylim(1200,2200) +
  theme_bw() +
  scale_color_discrete(name = "Format") +
  transition_reveal(Date)
```
```{r}
anim_save("smoother_elo_plot.gif")
```


```{r smoothest_elo_plot}

# Elo vs time

all_games %>%
  group_by(month, website, format) %>% 
  summarize(elo_avg = mean(my_elo), .groups = "keep") %>% 
  ggplot(aes(x = month, 
             y = elo_avg,
                 group = format,
                 color = factor(format))) +
  geom_line(na.rm = TRUE) +
  facet_wrap(~ website) +
  labs(title = "Elo Rating Over Time, by Website and Time Control", 
       y = "Elo Rating",
       caption = "Ratings taken as monthly averages") +
  ylim(1200,2200) +
  theme_bw() +
  scale_color_discrete(name = "Format") +
  transition_reveal(month)

anim_save(filename = "smoothest_elo_plot.gif")
```


```{r pop_openings}
# My most popular openings with each color

openings <- all_games %>% 
  group_by(me_white, ECO) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count)) %>% 
  slice(1:15)


  openings %>% 
  ggplot(aes(x = fct_reorder(ECO, count), y = count, fill = me_white)) +
  geom_col(position = position_dodge2(preserve = "single")) +
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
# UNNECESSARY

white_openings <- openings %>% 
  filter(me_white) %>% 
  droplevels()

black_openings <- openings %>% 
  filter(!me_white) %>% 
  droplevels()


ggplot(data = white_openings) +
  geom_col(data = white_openings,
           mapping = aes(x = fct_reorder(ECO, desc(count)), y = count))

ggplot(data = black_openings) + 
  geom_col(data = black_openings,
           mapping = aes(x = fct_reorder(ECO, desc(count)), y = count))
```

```{r best_worst_openings}
all_games_dense %>% 
  summarize(score = mean(outcome))

all_games_dense %>% 
  group_by(ECO, ECO_letter) %>% 
  summarize(avg_score = mean(outcome),
            count = n()) %>% 
  filter(count >= 20) %>% 
  arrange(avg_score) %>% 
  filter(!between(avg_score, 0.48, 0.58)) %>% 
  ggplot(aes(y = avg_score, x = count)) +
  geom_text_repel(aes(label = ECO, color = ECO_letter), size = 3) +
  geom_hline(yintercept = 0.533, lty = "dashed", color = "dodgerblue") +
  geom_text(x = 350, y = 0.52, label = "Average Win Rate Over All Games",
            color = "dodgerblue") +
  geom_text(x = 350, y = 0.545, label = "53.3%", color = "dodgerblue") +
  labs(title = "My Most and Least Successful Openings",
       subtitle = "Minimum 20 Games Played per Opening",
       x = "Number of Games",
       y = "Win rate",
       caption = "Colored by similarity in opening moves. See Discussion tab
       for more information on what each code means.") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_color_manual(values = wes_palette("Darjeeling1")) +
  theme_classic() +
  theme(legend.position = "none")

ggsave(filename = "openings.png")
```

```{r, cache = TRUE}
# Trying to see what distribution of games outcomes is.
elo_fit <- stan_glm(formula = outcome ~ elo_diff,
         data = all_games_dense,
         refresh = 0)

new_data = tibble(elo_diff = -200:200)
```

```{r, cache = TRUE}
posterior_predict(elo_fit,
                  newdata = new_data) %>% 
  as_tibble() %>% 
  mutate_all(as.numeric) %>% 
  pivot_longer(cols = everything(),
               names_to = "elo_diff",
               values_to = "pred") %>%
  mutate(elo_diff = as.numeric(elo_diff) - 201) %>%
  ggplot(aes(x = elo_diff, y = pred)) +
  geom_density_2d_filled()
```    


```{r handpicked_openings}
handpicked <- all_games_dense %>% 
  filter(ECO %in% c("B01",
                    "D02",
                    "B20",
                    "D32",
                    "D06",
                    "C45",
                    "C53",
                    "C55",
                    "C11",
                    "B34",
                    "D01",
                    "D03",
                    "C20",
                    "C10"))

handpicked <- handpicked %>% 
  group_by(ECO, me_white) %>% 
  summarize(avg_score = mean(outcome),
            num_games = n())
  
handpicked %>% 
  ggplot(aes(x = num_games, y = avg_score, color = me_white)) +
  geom_text_repel(aes(label = ECO), size = 2)

```


```{r time_series, cache = TRUE}
all_games_dense %>% 
  group_by(month) %>% 
  summarize(count = n(),
            .groups = "keep") %>% 
  ggplot(aes(x = month, y = count, fill = count)) +
  geom_col() +
  labs(title = "Games Played Per Month",
       subtitle = "Since First Account Opened in 2018",
       x = "",
       y = "Number of Games Played") +
  theme_economist() +
  theme(panel.grid = element_blank(),
        panel.grid.major.y = element_line(color = "white"),
        panel.ontop = TRUE,
        legend.position = "none",
        axis.text.x = element_text(angle = 45)) +
  scale_x_date(date_breaks = "4 months",
               date_labels = "%b-%Y") +
  transition_states(month, wrap = FALSE) +
  shadow_mark() +
  enter_grow() +
  enter_fade()

anim_save(filename = "game_count.gif")
```

```{r time_series2}
all_games_dense %>% 
  group_by(month) %>% 
  summarize(win_pct = mean(outcome),
            count = n()) %>% 
  ggplot(aes(x = month, y = win_pct, fill = count)) +
  geom_col() +
  labs(title = "Win Percentage Per Month",
       subtitle = "Since First Account Opened in 2018",
       x = "",
       y = "Win Rate") +
  theme_economist() +
  theme(panel.grid = element_blank(),
        panel.grid.major.y = element_line(color = "white"),
        panel.ontop = TRUE,
        legend.position = "none",
        axis.text.x = element_text(angle = 45)) +
  scale_x_date(date_breaks = "4 months",
               date_labels = "%b-%Y") +
  scale_y_continuous(labels = scales::percent_format())
  #transition_states(month, wrap = FALSE) +
  #shadow_mark() +
  #enter_grow() +
  #enter_fade()

#anim_save(filename = "game_count.gif")


```

$$performance\_rating = \frac{sum(opp\_rating) + 400(num\_wins - num\_losses)}{num\_games} $$

```{r elo_performance}

all_games_dense %>%
  mutate(quarter = floor_date(Date, "quarter")) %>% 
  group_by(quarter, website, format) %>%
  filter(!is.na(opp_elo)) %>% 
  summarize(sum_opp_elo= sum(opp_elo),
            total_score = sum(outcome),
            num_games = n(),
            elo_perf = (sum_opp_elo + 400*(2*total_score - num_games))/num_games,
            .groups = "keep") %>%  
  ggplot(aes(x = quarter, y = elo_perf, fill = num_games)) +
  geom_col(position = position_dodge2(preserve = "single")) +
  coord_cartesian(ylim = c(1000, 2200)) +
  facet_wrap(~ website + format,
              nrow = 2) +
  labs(title = "Performance Rating By Website and Format Over Time",
       subtitle = "Quarter Starting: {closest_state}",
       x = "Quarter",
       y = "Performance Rating (Elo/Glicko)") +
  transition_states(quarter, wrap = FALSE) +
  shadow_mark() +
  enter_grow() +
  enter_fade() +
  ease_aes('linear')

anim_save(filename = "quarter_perf.gif", end_pause = 100)

```












